import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class SettingsProvider extends ChangeNotifier {
  static const String _themeKey = 'theme_mode';
  static const String _localeKey = 'locale_code';

  ThemeMode _themeMode = ThemeMode.light;
  Locale _locale = const Locale('id');

  ThemeMode get themeMode => _themeMode;
  Locale get locale => _locale;

  bool get isDarkMode => _themeMode == ThemeMode.dark;

  SettingsProvider() {
    _loadSettings();
  }

  Future<void> _loadSettings() async {
    final prefs = await SharedPreferences.getInstance();
    
    // Load Theme
    final themeIndex = prefs.getInt(_themeKey);
    if (themeIndex != null) {
      _themeMode = ThemeMode.values[themeIndex];
    }

    // Load Locale
    final localeCode = prefs.getString(_localeKey) ?? 'id';
    _locale = Locale(localeCode);
    
    notifyListeners();
  }

  Future<void> toggleTheme(bool isDark) async {
    _themeMode = isDark ? ThemeMode.dark : ThemeMode.light;
    notifyListeners();

    final prefs = await SharedPreferences.getInstance();
    await prefs.setInt(_themeKey, _themeMode.index);
  }

  Future<void> setLocale(String languageCode) async {
    _locale = Locale(languageCode);
    notifyListeners();

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_localeKey, languageCode);
  }

  String translate(String key) {
    final Map<String, Map<String, String>> localizedValues = {
      'id': {
        'settings': 'Pengaturan',
        'general_prefs': 'Preferensi Umum',
        'notifications': 'Notifikasi',
        'notifications_sub': 'Update status booking & promo',
        'mark_all_read': 'Tandai Baca',
        'no_notifications': 'Belum ada notifikasi',
        'dark_mode': 'Mode Gelap',
        'dark_mode_sub': 'Tampilan gelap yang nyaman',
        'app_language': 'Bahasa Aplikasi',
        'security_account': 'Keamanan & Akun',
        'change_password': 'Ubah Kata Sandi',
        'change_password_sub': 'Perbarui keamanan akun Anda',
        'about_us': 'Tentang Kami',
        'rate_us': 'Beri Rating',
        'rate_us_sub': 'Bantu kami menjadi lebih baik',
        'select_language': 'Pilih Bahasa',
        'my_profile': 'Profil Saya',
        'account_settings': 'Pengaturan Akun',
        'edit_account': 'Edit Akun',
        'edit_account_sub': 'Ubah nama, email, dan lainnya',
        'settings_sub': 'Notifikasi, bahasa, dan keamanan',
        'support_more': 'Dukungan & Lainnya',
        'help_center': 'Pusat Bantuan',
        'help_center_sub': 'FAQ dan kontak dukungan',
        'logout': 'Keluar',
        'logout_sub': 'Keluar dari akun Anda',
        'guest': 'Pengguna',
        'halo': 'Halo, {name}! 🐾',
        'harimu_menyenangkan': 'Semoga harimu menyenangkan',
        'search': 'Cari',
        'konsultasi_cepat': 'Konsultasi hewan\npeliharaan Anda dengan\ncepat dan mudah.',
        'antrian': 'Antrian',
        'konsultasi': 'Konsultasi',
        'rekam_medis': 'Rekam Medis',
        'dokter_paw': 'DokterPaw',
        'edukasi': 'Edukasi',
        'lihat_semua': 'Lihat semua',
        'riwayat_booking': 'Riwayat Booking',
        'belum_ada_booking': 'Belum ada booking aktif',
        'booking_sekarang': 'Booking sekarang untuk hewan peliharaan Anda',
        'kali_dilihat': 'kali dilihat',
        'edit_profile': 'Edit Profil',
        'personal_info': 'Informasi Pribadi',
        'full_name': 'Nama Lengkap',
        'email_address': 'Alamat Email',
        'phone_number': 'Nomor Telepon',
        'save_changes': 'Simpan Perubahan',
        'profile_updated': 'Profil berhasil diperbarui!',
        'profile_update_failed': 'Gagal memperbarui profil.',
        'name_empty_error': 'Nama tidak boleh kosong',
        'help_center_title': 'Pusat Bantuan',
        'ready_to_help': 'Kami siap membantu Anda',
        'need_fast_help': 'Butuh Bantuan Cepat?',
        'chat_direct': 'Chat langsung',
        'send_message': 'Kirim pesan',
        'faq_title': 'Pertanyaan Umum',
        'legal_policy': 'Hukum & Kebijakan',
        'terms_sub': 'Aturan penggunaan aplikasi',
        'privacy_sub': 'Cara kami menjaga data Anda',
        'cannot_open_wa': 'Tidak dapat membuka WhatsApp',
        'cannot_open_email': 'Tidak dapat membuka aplikasi Email',
        'faq1_q': 'Bagaimana cara booking?',
        'faq1_a': 'Pilih layanan yang Anda inginkan di halaman utama, pilih jadwal yang tersedia, lalu lakukan konfirmasi pembayaran.',
        'faq2_q': 'Apakah bisa membatalkan janji?',
        'faq2_a': 'Ya, pembatalan dapat dilakukan maksimal 24 jam sebelum jadwal melalui menu riwayat transaksi.',
        'faq3_q': 'Metode pembayaran apa saja?',
        'faq3_a': 'Kami mendukung berbagai metode pembayaran mulai dari Transfer Bank hingga E-Wallet (Gopay, OVO, Dana).',
        'privacy_title': 'Kebijakan Privasi',
        'last_updated': 'Terakhir diperbarui: 30 April 2026',
        'privacy_sec1_t': 'Informasi yang Kami Kumpulkan',
        'privacy_sec1_c': 'Kami mengumpulkan informasi yang Anda berikan secara langsung kepada kami, seperti saat Anda membuat akun, melakukan booking, atau menghubungi layanan pelanggan. Ini termasuk nama, alamat email, nomor telepon, dan informasi hewan peliharaan Anda.',
        'privacy_sec2_t': 'Penggunaan Informasi',
        'privacy_sec2_c': 'Kami menggunakan informasi tersebut untuk memproses booking Anda, memberikan layanan konsultasi, mengelola akun Anda, dan mengirimkan informasi penting terkait layanan kami.',
        'privacy_sec3_t': 'Keamanan Data',
        'privacy_sec3_c': 'Kami menerapkan langkah-langkah keamanan teknis dan organisasional yang tepat untuk melindungi data pribadi Anda dari akses, penggunaan, atau pengungkapan yang tidak sah.',
        'privacy_sec4_t': 'Berbagi Informasi',
        'privacy_sec4_c': 'Kami tidak menjual atau menyewakan informasi pribadi Anda kepada pihak ketiga. Kami hanya berbagi informasi dengan dokter hewan atau mitra layanan yang diperlukan untuk memenuhi kebutuhan medis hewan Anda.',
        'privacy_sec5_t': 'Hak Anda',
        'privacy_sec5_c': 'Anda memiliki hak untuk mengakses, memperbarui, atau meminta penghapusan data pribadi Anda kapan saja melalui pengaturan akun atau dengan menghubungi kami.',
        'privacy_sec6_t': 'Cookies',
        'privacy_sec6_c': 'Aplikasi kami dapat menggunakan cookies dan teknologi serupa untuk meningkatkan pengalaman pengguna dan menganalisis penggunaan aplikasi.',
        'terms_title': 'Syarat & Ketentuan',
        'terms_sec1_t': 'Penerimaan Ketentuan',
        'terms_sec1_c': 'Dengan menggunakan aplikasi DVPets, Anda setuju untuk terikat oleh Syarat & Ketentuan ini. Jika Anda tidak menyetujui bagian apa pun dari ketentuan ini, Anda tidak diperbolehkan menggunakan layanan kami.',
        'terms_sec2_t': 'Layanan Kami',
        'terms_sec2_c': 'DVPets menyediakan platform untuk booking layanan kesehatan hewan, konsultasi dokter hewan, dan manajemen rekam medis hewan peliharaan Anda.',
        'terms_sec3_t': 'Akun Pengguna',
        'terms_sec3_c': 'Anda bertanggung jawab untuk menjaga kerahasiaan informasi akun dan kata sandi Anda. Anda setuju untuk bertanggung jawab atas semua aktivitas yang terjadi di bawah akun Anda.',
        'terms_sec4_t': 'Kebijakan Pembatalan',
        'terms_sec4_c': 'Pembatalan janji temu dapat dilakukan melalui aplikasi paling lambat 24 jam sebelum waktu yang dijadwalkan. Pembatalan yang dilakukan kurang dari 24 jam mungkin akan dikenakan biaya administrasi.',
        'terms_sec5_t': 'Batasan Tanggung Jawab',
        'terms_sec5_c': 'DVPets tidak bertanggung jawab atas kerugian atau kerusakan yang timbul dari penggunaan layanan kami, kecuali jika diwajibkan oleh hukum yang berlaku.',
        'terms_sec6_t': 'Perubahan Ketentuan',
        'terms_sec6_c': 'Kami berhak untuk mengubah Syarat & Ketentuan ini kapan saja. Perubahan akan berlaku segera setelah dipublikasikan di aplikasi.',
        
        // Chatbot
        'welcome_virtual_clinic': 'Selamat Datang di Klinik Virtual DVPets',
        'chatbot_desc': 'Ceritakan kondisi hewan kesayanganmu.\n DokterPaw siap membantu diagnosa & memberikan saran.',
        'disease_types': 'Jenis Penyakit',
        'accuracy_diagnosis': 'Akurasi Diagnosis',
        'fast_consultation': 'Konsultasi',
        'analyzing': 'Sedang menganalisa...',
        'tell_pet_condition': 'Ceritakan kondisi hewan kamu...',
        'refresh': 'Refresh',
        'delete_chat': 'Hapus Chat',
        'delete_history_title': 'Hapus Riwayat Chat',
        'delete_history_confirm': 'Semua riwayat percakapan akan dihapus permanen. Yakin?',
        'cancel': 'Batal',
        'delete': 'Hapus',
        'history_deleted': 'Riwayat chat berhasil dihapus ✨',
        'history_delete_failed': 'Gagal menghapus riwayat di server',
        'virtual_assistant': 'Assisten Virtual DVPets',
        'suggestions': 'Saran Pertanyaan',
        'camera_label': 'Kamera',
        'gallery_label': 'Galeri',
        'send_photo_to_ai': 'Kirim Foto ke DokterPaw',
        'vision_mode_error': 'Fitur gambar tidak tersedia dalam mode Groq',
        'chat_error_status': 'Terjadi kesalahan ({code}). Coba lagi ya!',
        'connection_error': 'Koneksi terputus. Pastikan server aktif dan coba lagi.',
        'suggest_cat': 'Kucing saya tidak mau makan dan lemas',
        'suggest_dog': 'Anjing saya muntah dan diare sejak tadi pagi',
        'suggest_pet_fever': 'Hewan saya demam dan batuk sudah 2 hari',
        'suggest_rabbit': 'Kelinci saya ada luka dan terlihat lesu',
        'suggest_worm_med': 'Cara pemberian obat cacing yang benar?',
        'suggest_groom_tips': 'Tips merawat bulu hewan agar tidak rontok',
        'archive': 'Arsipkan',
        'unarchive': 'Buka Arsip',
        'archive_list': 'Daftar Arsip',
        'no_archived_chats': 'Belum ada chat yang diarsipkan',
        'consultation_archived': 'Chat berhasil diarsipkan',
        'consultation_unarchived': 'Chat berhasil dikeluarkan dari arsip',

        // Doctor List
        'consultation_title': 'Konsultasi Dokter',
        'choose_doctor': 'Pilih dokter untuk memulai konsultasi',
        'retry': 'Coba Lagi',
        'no_doctor_available': 'Belum ada dokter tersedia',
        'start_consultation': 'Mulai Konsultasi',
        'consultation_confirm': 'Apakah Anda ingin memulai sesi konsultasi baru dengan {name}?',
        'patient': 'Pasien',
        'online': 'Online',
        'offline': 'Offline',
        'typing': 'Sedang mengetik...',
        'type_message': 'Ketik pesan...',
        'start_chat_desc': 'Ketik pesan untuk memulai konsultasi\ndengan {name}',
        'fail_start_chat': 'Gagal memulai konsultasi',
        'fail_send_chat': 'Gagal mengirim: {error}',
        'active_consultation': 'Konsultasi Aktif',
        'cari_dokter': 'Cari Dokter',
        'start_chat_now': 'Mulai chat sekarang',

        // Education
        'education_title': 'Edukasi',
        'education_desc': 'Pelajari lebih lanjut tentang hewan peliharaan',
        'search_placeholder': 'Cari tutorial atau video...',
        'read': 'Baca',
        'times_read': '{count} kali dibaca',
        'watch_on_youtube': 'Tonton Video di YouTube',
        'article_content': 'Konten Artikel',
        'published_at': 'Dipublikasikan: {date}',
        'tips': 'Tips',
        'article': 'Artikel',
        'video': 'Video',
        'news': 'Berita',
        'beginner': 'Pemula',
        'intermediate': 'Menengah',
        'advanced': 'Mahir',
        'minutes_read': 'menit baca',

        // Booking History
        'booking_history_title': 'Riwayat Booking',
        'check_booking_status': 'Cek status pemesanan Anda',
        'enter_email': 'Masukkan Email',
        'email_placeholder': 'contoh@email.com',
        'search_booking_history_hint': 'Masukkan email untuk melihat\nriwayat booking',
        'no_booking_history': 'Tidak ada riwayat booking',
        'for_this_email': 'untuk email ini',
        'booking_code_label': 'Kode Booking',
        'service_label': 'Layanan',
        'total_label': 'Total',

        // Queue
        'queue_info_title': 'Info Antrian Klinik',
        'realtime_queue_desc': 'Pantau antrian real-time',
        'check_my_queue': 'Cek Antrian Saya',
        'enter_booking_code': 'Masukkan kode booking...',
        'check_btn': 'Cek',
        'your_queue': 'Antrian Anda',
        'queue_number': 'Nomor Antrian',
        'position': 'Posisi',
        'estimated': 'Estimasi',
        'serving': 'Dilayani',
        'realtime_queue': 'Antrian Real-time',
        'no_queue': 'Tidak ada antrian',
        'waiting_status': 'Menunggu',
        'finished_status': 'Selesai',
        'all_services': 'Semua Layanan',
        'general_consultation': 'Konsultasi Umum',
        'vaccination': 'Vaksinasi',
        'grooming': 'Grooming',
        'dental_care': 'Perawatan Gigi',
        'surgery_label': 'Operasi',
        'laboratory_label': 'Laboratorium',
        'code_label': 'Kode',
        'time_label': 'Waktu',
        'status_label': 'Status',
        'booking_code_not_found': 'Kode booking tidak ditemukan',

        // Doctor Home
        'welcome_doctor': 'Selamat Datang, {name}',
        'consultation_list': 'Daftar Konsultasi',
        'search_patient': 'Cari pasien...',
        'no_consultation': 'Belum ada konsultasi',
        'give_label': 'Beri Label',
        'label_hint': 'Contoh: Demam, Rabies...',
        'save': 'Simpan',
        'hide': 'Sembunyikan',
        'consultation_hidden': 'Konsultasi berhasil disembunyikan',

        // Booking
        'booking_service_title': 'Booking Layanan',
        'step_service': 'Pilih Layanan',
        'step_schedule': 'Dokter & Jadwal',
        'step_data': 'Data Pemilik & Hewan',
        'step_service_desc': 'Pilih layanan untuk hewan Anda',
        'step_schedule_desc': 'Tentukan dokter dan jadwal kunjungan',
        'step_data_desc': 'Lengkapi data pemilik dan hewan',
        'label_service': 'Layanan',
        'label_schedule': 'Jadwal',
        'label_data': 'Data',
        'no_service_found': 'Tidak ada layanan',
        'close_btn': 'Tutup',
        'price_label': 'Harga',
        'duration_label': 'Durasi',
        'service_detail_title': 'Detail Layanan',
        'available_doctors_hint': 'Dokter yang tersedia disesuaikan dengan layanan yang dipilih',
        'visit_date_label': 'Tanggal Kunjungan',
        'visit_time_label': 'Waktu Kunjungan',
        'min_booking_hint': 'Minimal booking untuk besok hari',
        'required_fields_hint': 'Kolom bertanda * wajib diisi',
        'owner_data_title': 'Data Pemilik',
        'full_name_label': 'Nama Lengkap',
        'enter_name_hint': 'Masukkan nama Anda',
        'name_req': 'Nama wajib diisi',
        'email_req': 'Email wajib diisi',
        'phone_req': 'Telepon wajib diisi',
        'address_req': 'Alamat wajib diisi',
        'pet_name_req': 'Nama hewan wajib diisi',
        'pet_type_label': 'Jenis Hewan',
        'pet_gender_label': 'Jenis Kelamin',
        'cat_label': 'Kucing',
        'dog_label': 'Anjing',
        'male_label': 'Jantan',
        'female_label': 'Betina',
        'ras_req': 'Ras wajib diisi',
        'age_req': 'Umur wajib diisi',
        'color_req': 'Ciri/warna wajib diisi',
        'additional_notes_label': 'Catatan Tambahan',
        'optional_hint': 'Opsional — tidak wajib diisi',
        'complaint_hint': 'Tuliskan keluhan atau catatan khusus...',
        'booking_summary_title': 'Ringkasan Pemesanan',
        'fee_label': 'Biaya',
        'back_btn': 'Kembali',
        'next_btn': 'Lanjut',
        'book_now_btn': 'Booking Sekarang',
        'select_service_first': 'Pilih layanan terlebih dahulu',
      },
      'en': {
        'settings': 'Settings',
        'general_prefs': 'General Preferences',
        'notifications': 'Notifications',
        'notifications_sub': 'Update booking status & promos',
        'mark_all_read': 'Mark Read',
        'no_notifications': 'No notifications yet',
        'dark_mode': 'Dark Mode',
        'dark_mode_sub': 'Comfortable dark appearance',
        'app_language': 'App Language',
        'security_account': 'Security & Account',
        'change_password': 'Change Password',
        'change_password_sub': 'Update your account security',
        'about_us': 'About Us',
        'rate_us': 'Rate Us',
        'rate_us_sub': 'Help us become better',
        'select_language': 'Select Language',
        'my_profile': 'My Profile',
        'account_settings': 'Account Settings',
        'edit_account': 'Edit Account',
        'edit_account_sub': 'Change name, email, and more',
        'settings_sub': 'Notifications, language, and security',
        'support_more': 'Support & More',
        'help_center': 'Help Center',
        'help_center_sub': 'FAQ and support contact',
        'logout': 'Logout',
        'logout_sub': 'Log out of your account',
        'guest': 'Guest User',
        'halo': 'Hello, {name}! 🐾',
        'harimu_menyenangkan': 'Have a nice day',
        'search': 'Search',
        'konsultasi_cepat': 'Consult your pet\nquickly and easily.',
        'antrian': 'Queue',
        'konsultasi': 'Consultation',
        'rekam_medis': 'Medical Record',
        'dokter_paw': 'PawDoctor',
        'edukasi': 'Education',
        'lihat_semua': 'See all',
        'riwayat_booking': 'Booking History',
        'belum_ada_booking': 'No active bookings',
        'booking_sekarang': 'Book now for your pet',
        'kali_dilihat': 'views',
        'edit_profile': 'Edit Profile',
        'personal_info': 'Personal Information',
        'full_name': 'Full Name',
        'email_address': 'Email Address',
        'phone_number': 'Phone Number',
        'save_changes': 'Save Changes',
        'profile_updated': 'Profile updated successfully!',
        'profile_update_failed': 'Failed to update profile.',
        'name_empty_error': 'Name cannot be empty',
        'help_center_title': 'Help Center',
        'ready_to_help': 'We are ready to help you',
        'need_fast_help': 'Need Fast Help?',
        'chat_direct': 'Chat directly',
        'send_message': 'Send message',
        'faq_title': 'Common Questions (FAQ)',
        'legal_policy': 'Legal & Policy',
        'terms_sub': 'Rules for using the application',
        'privacy_sub': 'How we take care of your data',
        'cannot_open_wa': 'Cannot open WhatsApp',
        'cannot_open_email': 'Cannot open Email application',
        'faq1_q': 'How to book?',
        'faq1_a': 'Select the service you want on the home page, choose an available schedule, then confirm payment.',
        'faq2_q': 'Can I cancel an appointment?',
        'faq2_a': 'Yes, cancellations can be made up to 24 hours before the schedule through the transaction history menu.',
        'faq3_q': 'What are the payment methods?',
        'faq3_a': 'We support various payment methods from Bank Transfer to E-Wallet (Gopay, OVO, Dana).',
        'privacy_title': 'Privacy Policy',
        'last_updated': 'Last updated: April 30, 2026',
        'privacy_sec1_t': 'Information We Collect',
        'privacy_sec1_c': 'We collect information that you provide directly to us, such as when you create an account, make a booking, or contact customer service. This includes your name, email address, phone number, and information about your pet.',
        'privacy_sec2_t': 'Use of Information',
        'privacy_sec2_c': 'We use that information to process your bookings, provide consultation services, manage your account, and send important information related to our services.',
        'privacy_sec3_t': 'Data Security',
        'privacy_sec3_c': 'We implement appropriate technical and organizational security measures to protect your personal data from unauthorized access, use, or disclosure.',
        'privacy_sec4_t': 'Sharing Information',
        'privacy_sec4_c': 'We do not sell or rent your personal information to third parties. We only share information with veterinarians or service partners as necessary to fulfill your pet\'s medical needs.',
        'privacy_sec5_t': 'Your Rights',
        'privacy_sec5_c': 'You have the right to access, update, or request the deletion of your personal data at any time through account settings or by contacting us.',
        'privacy_sec6_t': 'Cookies',
        'privacy_sec6_c': 'Our application may use cookies and similar technologies to enhance the user experience and analyze application usage.',
        'terms_title': 'Terms & Conditions',
        'terms_sec1_t': 'Acceptance of Terms',
        'terms_sec1_c': 'By using the DVPets application, you agree to be bound by these Terms & Conditions. If you do not agree to any part of these terms, you are not permitted to use our services.',
        'terms_sec2_t': 'Our Services',
        'terms_sec2_c': 'DVPets provides a platform for booking pet healthcare services, veterinarian consultations, and managing your pet\'s medical records.',
        'terms_sec3_t': 'User Account',
        'terms_sec3_c': 'You are responsible for maintaining the confidentiality of your account information and password. You agree to be responsible for all activities that occur under your account.',
        'terms_sec4_t': 'Cancellation Policy',
        'terms_sec4_c': 'Appointment cancellations can be made through the application no later than 24 hours before the scheduled time. Cancellations made less than 24 hours in advance may be subject to an administrative fee.',
        'terms_sec5_t': 'Limitation of Liability',
        'terms_sec5_c': 'DVPets is not responsible for any losses or damages arising from the use of our services, unless required by applicable law.',
        'terms_sec6_t': 'Changes to Terms',
        'terms_sec6_c': 'We reserve the right to change these Terms & Conditions at any time. Changes will be effective immediately upon publication in the application.',
        
        // Chatbot
        'welcome_virtual_clinic': 'Welcome to DVPets Virtual Clinic',
        'chatbot_desc': 'Tell us about your pet\'s condition.\n DokterPaw is ready to help with diagnosis & advice.',
        'disease_types': 'Disease Types',
        'accuracy_diagnosis': 'Diag. Accuracy',
        'fast_consultation': 'Consultation',
        'analyzing': 'Analyzing...',
        'tell_pet_condition': 'Tell us your pet\'s condition...',
        'refresh': 'Refresh',
        'delete_chat': 'Delete Chat',
        'delete_history_title': 'Delete Chat History',
        'delete_history_confirm': 'All conversation history will be permanently deleted. Are you sure?',
        'cancel': 'Cancel',
        'delete': 'Delete',
        'history_deleted': 'Chat history successfully deleted ✨',
        'history_delete_failed': 'Failed to delete history on server',
        'virtual_assistant': 'DVPets Virtual Assistant',
        'suggestions': 'Suggested Questions',
        'camera_label': 'Camera',
        'gallery_label': 'Gallery',
        'send_photo_to_ai': 'Send Photo to DokterPaw',
        'vision_mode_error': 'Image feature not available in Groq mode',
        'chat_error_status': 'An error occurred ({code}). Please try again!',
        'connection_error': 'Connection lost. Make sure server is active and try again.',
        'suggest_cat': 'My cat is lethargic and won\'t eat',
        'suggest_dog': 'My dog has been vomiting and has diarrhea since this morning',
        'suggest_pet_fever': 'My pet has a fever and a cough for 2 days',
        'suggest_rabbit': 'My rabbit has a wound and looks weak',
        'suggest_worm_med': 'How to correctly give deworming medicine?',
        'suggest_groom_tips': 'Tips for grooming pet fur to prevent shedding',
        'archive': 'Archive',
        'unarchive': 'Unarchive',
        'archive_list': 'Archive List',
        'no_archived_chats': 'No archived chats found',
        'consultation_archived': 'Chat has been archived',
        'consultation_unarchived': 'Chat has been unarchived',

        // Doctor List
        'consultation_title': 'Doctor Consultation',
        'choose_doctor': 'Select a doctor to start consultation',
        'retry': 'Retry',
        'no_doctor_available': 'No doctors available yet',
        'start_consultation': 'Start Consultation',
        'consultation_confirm': 'Do you want to start a new consultation session with {name}?',
        'patient': 'Patient',
        'online': 'Online',
        'offline': 'Offline',
        'typing': 'Typing...',
        'type_message': 'Type a message...',
        'start_chat_desc': 'Type a message to start consultation\nwith {name}',
        'fail_start_chat': 'Failed to start consultation',
        'fail_send_chat': 'Failed to send: {error}',
        'active_consultation': 'Active Consultations',
        'cari_dokter': 'Find Doctor',
        'start_chat_now': 'Start chat now',

        // Education
        'education_title': 'Education',
        'education_desc': 'Learn more about pet care and health',
        'search_placeholder': 'Search tutorials or videos...',
        'read': 'Read',
        'times_read': '{count} times read',
        'watch_on_youtube': 'Watch Video on YouTube',
        'article_content': 'Article Content',
        'published_at': 'Published: {date}',
        'tips': 'Tips',
        'article': 'Article',
        'video': 'Video',
        'news': 'News',
        'beginner': 'Beginner',
        'intermediate': 'Intermediate',
        'advanced': 'Advanced',
        'minutes_read': 'min read',

        // Booking History
        'booking_history_title': 'Booking History',
        'check_booking_status': 'Check your booking status',
        'enter_email': 'Enter Email',
        'email_placeholder': 'example@email.com',
        'search_booking_history_hint': 'Enter email to see\nyour booking history',
        'no_booking_history': 'No booking history',
        'for_this_email': 'for this email',
        'booking_code_label': 'Booking Code',
        'service_label': 'Service',
        'total_label': 'Total',

        // Queue
        'queue_info_title': 'Clinic Queue Info',
        'realtime_queue_desc': 'Monitor real-time queue',
        'check_my_queue': 'Check My Queue',
        'enter_booking_code': 'Enter booking code...',
        'check_btn': 'Check',
        'your_queue': 'Your Queue',
        'queue_number': 'Queue Number',
        'position': 'Position',
        'estimated': 'Estimated',
        'serving': 'Serving',
        'realtime_queue': 'Real-time Queue',
        'no_queue': 'No queue available',
        'waiting_status': 'Waiting',
        'finished_status': 'Finished',
        'all_services': 'All Services',
        'general_consultation': 'General Consultation',
        'vaccination': 'Vaccination',
        'grooming': 'Grooming',
        'dental_care': 'Dental Care',
        'surgery_label': 'Surgery',
        'laboratory_label': 'Laboratory',
        'code_label': 'Code',
        'time_label': 'Time',
        'status_label': 'Status',
        'booking_code_not_found': 'Booking code not found',

        // Doctor Home
        'welcome_doctor': 'Welcome, {name}',
        'consultation_list': 'Consultation List',
        'search_patient': 'Search patient...',
        'no_consultation': 'No consultations available',
        'give_label': 'Give Label',
        'label_hint': 'Example: Fever, Rabies...',
        'save': 'Save',
        'hide': 'Hide',
        'consultation_hidden': 'Consultation successfully hidden',

        // Booking
        'booking_service_title': 'Service Booking',
        'step_service': 'Select Service',
        'step_schedule': 'Doctor & Schedule',
        'step_data': 'Owner & Pet Data',
        'step_service_desc': 'Choose a service for your pet',
        'step_schedule_desc': 'Set doctor and visit schedule',
        'step_data_desc': 'Complete owner and pet details',
        'label_service': 'Service',
        'label_schedule': 'Schedule',
        'label_data': 'Data',
        'no_service_found': 'No services found',
        'close_btn': 'Close',
        'price_label': 'Price',
        'duration_label': 'Duration',
        'service_detail_title': 'Service Detail',
        'available_doctors_hint': 'Available doctors are adjusted to the selected service',
        'visit_date_label': 'Visit Date',
        'visit_time_label': 'Visit Time',
        'min_booking_hint': 'Minimum booking is for tomorrow',
        'required_fields_hint': 'Columns marked with * are required',
        'owner_data_title': 'Owner Data',
        'full_name_label': 'Full Name',
        'enter_name_hint': 'Enter your name',
        'name_req': 'Name is required',
        'email_req': 'Email is required',
        'phone_req': 'Phone is required',
        'address_req': 'Address is required',
        'pet_name_req': 'Pet name is required',
        'pet_type_label': 'Pet Type',
        'pet_gender_label': 'Gender',
        'cat_label': 'Cat',
        'dog_label': 'Dog',
        'male_label': 'Male',
        'female_label': 'Female',
        'ras_req': 'Breed is required',
        'age_req': 'Age is required',
        'color_req': 'Color/description is required',
        'additional_notes_label': 'Additional Notes',
        'optional_hint': 'Optional — not mandatory',
        'complaint_hint': 'Write your complaint or special notes...',
        'booking_summary_title': 'Booking Summary',
        'fee_label': 'Fee',
        'back_btn': 'Back',
        'next_btn': 'Next',
        'book_now_btn': 'Book Now',
        'select_service_first': 'Select a service first',
      },
    };

    String text = localizedValues[_locale.languageCode]?[key] ?? key;
    return text;
  }
}
